# Generated by Django 3.1 on 2020-08-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200830_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timeStamp',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
